run:
  # which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but default dirs are skipped independently
  # from this option's value (see skip-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work
  # on Windows.
  skip-dirs: []

linters:
  enable:
    - lll
    - gofumpt
    - goconst
    - gosimple
    - misspell
    - stylecheck
    # style linters start
    - asciicheck
    - errname
    - forcetypeassert
    - whitespace
    - unconvert
    - predeclared
    - importas
    # style linters end
  disable:
    # deprecated linters start
    - scopelint
    - maligned
    # deprecated linters end
    - goimports
  presets:
    - import
    - bugs
    - unused
    - performance

# all available settings of specific linters
linters-settings:
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 4
  gci:
    # Checks that no inline Comments are present.
    # Default: false
    no-inline-comments: true
    # Checks that no prefix Comments(comment lines above an import) are present.
    # Default: false
    no-prefix-comments: true
    # Section configuration to compare against.
    # Section names are case-insensitive and may contain parameters in ().
    # Default: ["standard", "default"]
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/sdcxtech/nuonuo) # Groups all imports with the specified Prefix.
    # Separators that should be present between sections.
    # Default: ["newLine"]
    section-separators:
      - newLine
  gofumpt:
      # Select the Go version to target. The default is `1.15`.
      lang-version: "1.18"
      # Choose whether or not to use the extra rules that are disabled
      # by default
      extra-rules: false
      module-path: github.com/sdcxtech/nuonuo
